export const coatColors = [
    { label: "Black", value: "black" },
    { label: "Bay", value: "bay" },
    { label: "Chestnut", value: "chestnut" },
    { label: "Grey", value: "grey" },
    { label: "Palomino", value: "palomino" },
    { label: "Buckskin", value: "buckskin" },
    { label: "Roan", value: "roan" },
    { label: "Pinto", value: "pinto" },
    { label: "Dun", value: "dun" },
    { label: "Cremello", value: "cremello" },
    { label: "Appaloosa", value: "appaloosa" },
    { label: "Perlino", value: "perlino" },
    { label: "Smoky Black", value: "smoky_black" },
    { label: "Smoky Cream", value: "smoky_cream" },
    { label: "Steel Gray", value: "steel_gray" },
    { label: "Dapple Gray", value: "dapple_gray" },
    { label: "Flea-Bitten Gray", value: "flea_bitten_gray" },
    { label: "Rose Gray", value: "rose_gray" },
    { label: "True White", value: "true_white" },
    { label: "Dominant White", value: "dominant_white" },
    { label: "Red Roan", value: "red_roan" },
    { label: "Blue Roan", value: "blue_roan" },
    { label: "Bay Roan", value: "bay_roan" },
    { label: "Tobiano", value: "tobiano" },
    { label: "Overo", value: "overo" },
    { label: "Tovero", value: "tovero" },
    { label: "Sabino", value: "sabino" },
    { label: "Splash White", value: "splash_white" },
    { label: "Leopard", value: "leopard" },
    { label: "Blanket", value: "blanket" },
    { label: "Snowflake", value: "snowflake" },
    { label: "Frosted", value: "frosted" },
    { label: "Marble", value: "marble" },
    { label: "Red Dun", value: "red_dun" },
    { label: "Grulla", value: "grulla" },
    { label: "Silver Dapple", value: "silver_dapple" },
    { label: "Champagne", value: "champagne" },
    { label: "Pearl", value: "pearl" },
    { label: "Rabicano", value: "rabicano" },
    { label: "Brindle", value: "brindle" },
    { label: "Sooty", value: "sooty" },
    { label: "Mealy", value: "mealy" }
  ];